services:
  fake-real-news-detection:
    image: vindictive/fake-real-news-detection:acbf14e
    build: .
    container_name: fake-real-news-detection
    platform: linux/amd64 # Set linux/arm64 for MACOS M Chip
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 5G
    environment:
      - JUPYTER_ENABLE_LAB=yes
